### ISSUE TITLE
how to run local LLM

### ISSUE THREAD

**Issue by ajmal-yazdani** [NamanJain-Nash/Semantic-Kernel#1]
Hi Naman,

Thanks for sharing the code.

I would like to know how you're running local LLM and expose as a web api endpoint please?

` // The API URL of Custom/Local LLM
 string apiUrl = "http://localhost:1234/v1/chat/completions";`

**Comment by NamanJain-Nash** [comment]
Their are mainly 1-2 ways 
1) Make the Complete deployed on local machine using llama cpp
2) Use Services like LM Studio that also give chat and server support

**Comment by ajmal-yazdani** [comment]
Hi @NamanJain-Nash Thanks!!!

How are you running as endpoint like `v1/chat/completions`? are you using llama cpp?

**Comment by NamanJain-Nash** [comment]
Like I have used LM Studio but for this need a flask server that will do the job
